name: Sync Readme

on:
  push:
    branches: 
      - gh-pages

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync README
    steps:
      - uses: actions/github-script@0.2
        with:
          github-token: ${{github.token}}
          script: |
            const {data: commit} = await github.repos.getCommit({...context.repo, ref: context.ref});
            if (commit.files.filter((f) => f.name == "README.md").length) {
              const resp = await github.repos.getContents({...context.repo, path: 'README.md', ref: 'gh-pages'});
              const content = resp.data.content;
              const result = await github.repos.createOrUpdateFile({
                ...context.repo, 
                path: 'README.md', 
                branch: 'qt5',
                message: 'sync from gh-pages',
                content: content,
              });
            }
